workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: development
        xcode: 16.4
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.cocoapods/repos
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Setting up code signing"
          keychain initialize
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Install pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo remove trunk
          pod repo add trunk https://cdn.cocoapods.org/
          pod repo update
          pod cache clean --all
          pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk 