workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      xcode: 16.4                      # ✅ Moved here
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.alifi
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.cocoapods/repos
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Setting up code signing"
          keychain initialize
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Force iOS Deployment Target to 14.0
        script: |
          echo "Patching iOS deployment target to 14.0"
          sed -i '' 's/PLATFORM_IOS = .*/PLATFORM_IOS = 14.0;/g' ios/Flutter/Generated.xcconfig || true
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 14.0;/g' ios/Runner.xcodeproj/project.pbxproj || true
          plutil -replace MinimumOSVersion -string 14.0 ios/Runner/Info.plist || true
      - name: Install pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo remove trunk
          pod repo add trunk https://cdn.cocoapods.org/
          pod repo update
          pod cache clean --all
          pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
