name: alifi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  http: ^1.2.0
  flutter_svg: ^2.0.10+1
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.7
  blur: ^4.0.2
  firebase_core: ^3.15.1
  firebase_core_web: ^2.7.0
  firebase_auth: ^5.6.2
  firebase_auth_web: ^5.8.0
  path_provider: ^2.1.2  # Added for local file storage
  path: ^1.8.3  # Added for path manipulation
  google_sign_in: ^6.2.1  # Updated to latest stable version
  google_sign_in_web: ^0.12.3  # Updated to match google_sign_in
  cloud_firestore: ^5.6.11
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  device_info_plus: ^11.5.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  uuid: ^4.3.3  # Added for generating unique IDs
  google_generative_ai: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4  # Downgraded version

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/alifi_logo.png
    - assets/images/app_icon.png
    - assets/images/cat_icon.png
    - assets/images/dog_icon.png
    - assets/images/ai_lufi.png
    - assets/images/loading.png
    - assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
    - assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - assets/fonts/InterDisplay-Regular.ttf
    - assets/fonts/Montserrat-Black.ttf
    - assets/fonts/Montserrat-ExtraBold.ttf
    - assets/images/payment/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
    - family: InterDisplay
      fonts:
        - asset: assets/fonts/InterDisplay-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
