name: alifi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  http: ^1.2.0
  flutter_svg: ^2.0.10+1
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.7
  blur: ^4.0.2
  firebase_core: ^3.15.1
  firebase_core_web: ^2.7.0
  firebase_auth: ^5.6.2
  firebase_auth_web: ^5.8.0
  path_provider: ^2.1.2  # Added for local file storage
  path: ^1.8.3  # Added for path manipulation
  google_sign_in: ^6.2.1  # Updated to latest stable version
  google_sign_in_web: ^0.12.3  # Updated to match google_sign_in
  cloud_firestore: ^5.6.11
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  device_info_plus: ^11.5.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  uuid: ^4.3.3  # Added for generating unique IDs
  google_generative_ai: ^0.2.2
  flutter_launcher_icons: ^0.14.4
  google_maps_flutter: ^2.5.3  # Added for Google Maps integration
  url_launcher: ^6.2.5  # Added for launching URLs (maps, phone)
  timeago: ^3.6.1  # Added for formatting relative time
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  geocoding: ^4.0.0
  supabase_flutter: ^2.3.4  # Added for Supabase integration
  mime: ^1.0.5  # Added for file type detection

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^2.0.0

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/alifi_logo.png
    - assets/images/app_icon.png
    - assets/images/cat_icon.png
    - assets/images/dog_icon.png
    - assets/images/ai_lufi.png
    - assets/images/loading.png
    - assets/images/3d_dog.png
    - assets/images/3d_cat.png
    - assets/images/3d_cat_bw.png
    - assets/images/3d_dog_bw.png
    - assets/images/3d_hamster.png
    - assets/images/3d_fish.png
    - assets/images/3d_guinea_pig.png
    - assets/images/3d_duck.png
    - assets/images/3d_lizzard.png
    - assets/images/3d_monkey.png
    - assets/images/3d_rabbit.png
    - assets/images/bird_3d.png
    - assets/images/3d_hamster_bw.png
    - assets/images/3d_fish_bw.png
    - assets/images/3d_guinea_pig_bw.png
    - assets/images/3d_duck_bw.png
    - assets/images/3d_lizzard_bw.png
    - assets/images/3d_monkey_bw.png
    - assets/images/3d_rabbit_bw.png
    - assets/images/3d_bird_bw.png
    - assets/images/leaderboard_3d.png
    - assets/images/food.png
    - assets/images/toys.png
    - assets/images/health.png
    - assets/images/beds.png
    - assets/images/hygiene.png
    - assets/images/ai_pet.png
    - assets/images/leaderboard.png
    - assets/images/cib_logo.png
    - assets/images/sb_logo.png
    - assets/images/paypal_logo.png
    - assets/images/stripe_logo.png
    - assets/images/visa_mastercard.png
    - assets/images/adoption.png
    - assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
    - assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - assets/fonts/InterDisplay-Regular.ttf
    - assets/fonts/Montserrat-Black.ttf
    - assets/fonts/Montserrat-ExtraBold.ttf
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
    - family: InterDisplay
      fonts:
        - asset: assets/fonts/InterDisplay-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
