name: alifi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.7
  blur: ^3.1.0
  firebase_core: ^2.24.2
  firebase_core_web: ^2.10.0
  firebase_auth: ^4.15.3
  firebase_auth_web: ^5.8.12
  google_sign_in: ^6.1.6
  google_sign_in_web: ^0.12.1
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/alifi_logo.png
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
