name: alifi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  http: ^1.1.0
  flutter_svg: ^2.0.10+1
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.7
  blur: ^4.0.2
  firebase_core: ^3.15.1
  firebase_core_web: ^2.7.0
  firebase_auth: ^5.6.2
  firebase_auth_web: ^5.8.0
  path_provider: ^2.1.2  # Added for local file storage
  path: ^1.8.3  # Added for path manipulation
  google_sign_in: ^6.2.1  # Updated to latest stable version
  google_sign_in_web: ^0.12.3  # Updated to match google_sign_in
  cloud_firestore: ^5.6.12
  provider: ^6.1.2
  shared_preferences: ^2.2.0
  device_info_plus: ^11.5.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  permission_handler: ^12.0.1
  uuid: ^4.3.3  # Added for generating unique IDs
  google_generative_ai: ^0.2.2
  flutter_launcher_icons: ^0.14.4
  google_maps_flutter: ^2.5.3  # Added for Google Maps integration
  url_launcher: ^6.2.5  # Added for launching URLs (maps, phone)
  timeago: ^3.6.1  # Added for formatting relative time
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  geocoding: ^4.0.0
  supabase_flutter: ^2.3.4  # Added for Supabase integration
  mime: ^1.0.5  # Added for file type detection
  share_plus: ^7.2.1  # Added for sharing functionality
  soft_edge_blur: 0.1.3  # Added for progressive blur effects
  sensors_plus: ^4.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dotted_border: ^2.0.0+2
  sign_in_with_apple: ^6.1.1
  flutter_facebook_auth: ^7.0.0
  fl_chart: ^0.68.0  # Added for beautiful interactive charts
  firebase_messaging: ^15.2.10  # Updated to compatible version
  flutter_local_notifications: ^17.2.2  # Added for local notifications
  cloud_functions: ^5.6.2  # Added for Firebase Functions

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^2.0.0

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/alifi_logo.png
    - assets/images/app_icon.png
    - assets/images/cat_icon.png
    - assets/images/dog_icon.png
    - assets/images/ai_lufi.png
    - assets/images/loading.png
    - assets/images/3d_dog.png
    - assets/images/3d_cat.png
    - assets/images/3d_cat_bw.png
    - assets/images/3d_dog_bw.png
    - assets/images/3d_hamster.png
    - assets/images/3d_fish.png
    - assets/images/3d_guinea_pig.png
    - assets/images/3d_duck.png
    - assets/images/3d_lizzard.png
    - assets/images/3d_monkey.png
    - assets/images/3d_rabbit.png
    - assets/images/bird_3d.png
    - assets/images/3d_hamster_bw.png
    - assets/images/3d_fish_bw.png
    - assets/images/3d_guinea_pig_bw.png
    - assets/images/3d_duck_bw.png
    - assets/images/3d_lizzard_bw.png
    - assets/images/3d_monkey_bw.png
    - assets/images/3d_rabbit_bw.png
    - assets/images/3d_bird_bw.png
    - assets/images/leaderboard_3d.png
    - assets/images/food.png
    - assets/images/toys.png
    - assets/images/health.png
    - assets/images/beds.png
    - assets/images/hygiene.png
    - assets/images/ai_pet.png
    - assets/images/leaderboard.png
    - assets/images/cib_logo.png
    - assets/images/sb_logo.png
    - assets/images/paypal_logo.png
    - assets/images/stripe_logo.png
    - assets/images/visa_mastercard.png
    - assets/images/adoption.png
    - assets/images/gender_female.png
    - assets/images/gender_male.png
    - assets/images/card_example.PNG
    - assets/images/age.png
    - assets/images/weight.png
    - assets/images/pet_id_cat.png
    - assets/images/logo_cropped.png
    - assets/images/vet_3d.png
    - assets/images/vet_3d2.png
    - assets/images/stamp.png
    - assets/images/vet_normal.png
    - assets/images/vet_fav.png
    - assets/images/store_normal.png
    - assets/images/store_fav.png
    - assets/images/header_title.png
    - assets/images/store_3d.png
    - assets/images/store_3d2.png
    - assets/images/overview.png
    - assets/images/products.png
    - assets/images/orders.png
    - assets/images/messages.png
    - assets/images/dzd_symbol.png
    - assets/images/notification_icon.png
    - assets/images/back_icon.png
    - assets/images/menu.svg
    - assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
    - assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - assets/fonts/InterDisplay-Regular.ttf
    - assets/fonts/Montserrat-Black.ttf
    - assets/fonts/Montserrat-ExtraBold.ttf
    - assets/data/locations.json
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
    - family: InterDisplay
      fonts:
        - asset: assets/fonts/InterDisplay-Regular.ttf
        - asset: assets/fonts/InterDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/InterDisplay-Black.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
